/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DRouteImport } from './routes/d'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as GithubRouteImport } from './routes/github'
import { Route as GithubDiffViewerRouteImport } from './routes/github-diff-viewer'
import { Route as InstallRouteImport } from './routes/install'
import { Route as ShareGitDiffRouteImport } from './routes/share-git-diff'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CliDddRouteImport } from './routes/cli.ddd'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as DocsGithubDiffViewerRouteImport } from './routes/docs.github-diff-viewer'
import { Route as DocsShareGitDiffRouteImport } from './routes/docs.share-git-diff'
import { Route as ViewSlugRouteImport } from './routes/view.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DRoute = DRouteImport.update({
  id: '/d',
  path: '/d',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubDiffViewerRoute = GithubDiffViewerRouteImport.update({
  id: '/github-diff-viewer',
  path: '/github-diff-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareGitDiffRoute = ShareGitDiffRouteImport.update({
  id: '/share-git-diff',
  path: '/share-git-diff',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CliDddRoute = CliDddRouteImport.update({
  id: '/cli/ddd',
  path: '/cli/ddd',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGithubDiffViewerRoute = DocsGithubDiffViewerRouteImport.update({
  id: '/github-diff-viewer',
  path: '/github-diff-viewer',
  getParentRoute: () => DocsRoute,
} as any)
const DocsShareGitDiffRoute = DocsShareGitDiffRouteImport.update({
  id: '/share-git-diff',
  path: '/share-git-diff',
  getParentRoute: () => DocsRoute,
} as any)
const ViewSlugRoute = ViewSlugRouteImport.update({
  id: '/view/$slug',
  path: '/view/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/d': typeof DRoute
  '/docs': typeof DocsRouteWithChildren
  '/github': typeof GithubRoute
  '/github-diff-viewer': typeof GithubDiffViewerRoute
  '/install': typeof InstallRoute
  '/share-git-diff': typeof ShareGitDiffRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cli/ddd': typeof CliDddRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/github-diff-viewer': typeof DocsGithubDiffViewerRoute
  '/docs/share-git-diff': typeof DocsShareGitDiffRoute
  '/view/$slug': typeof ViewSlugRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/d': typeof DRoute
  '/github': typeof GithubRoute
  '/github-diff-viewer': typeof GithubDiffViewerRoute
  '/install': typeof InstallRoute
  '/share-git-diff': typeof ShareGitDiffRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cli/ddd': typeof CliDddRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/github-diff-viewer': typeof DocsGithubDiffViewerRoute
  '/docs/share-git-diff': typeof DocsShareGitDiffRoute
  '/view/$slug': typeof ViewSlugRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/d': typeof DRoute
  '/docs': typeof DocsRouteWithChildren
  '/github': typeof GithubRoute
  '/github-diff-viewer': typeof GithubDiffViewerRoute
  '/install': typeof InstallRoute
  '/share-git-diff': typeof ShareGitDiffRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/cli/ddd': typeof CliDddRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/github-diff-viewer': typeof DocsGithubDiffViewerRoute
  '/docs/share-git-diff': typeof DocsShareGitDiffRoute
  '/view/$slug': typeof ViewSlugRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/d'
    | '/docs'
    | '/github'
    | '/github-diff-viewer'
    | '/install'
    | '/share-git-diff'
    | '/sitemap.xml'
    | '/cli/ddd'
    | '/docs/cli'
    | '/docs/github-diff-viewer'
    | '/docs/share-git-diff'
    | '/view/$slug'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/d'
    | '/github'
    | '/github-diff-viewer'
    | '/install'
    | '/share-git-diff'
    | '/sitemap.xml'
    | '/cli/ddd'
    | '/docs/cli'
    | '/docs/github-diff-viewer'
    | '/docs/share-git-diff'
    | '/view/$slug'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/d'
    | '/docs'
    | '/github'
    | '/github-diff-viewer'
    | '/install'
    | '/share-git-diff'
    | '/sitemap.xml'
    | '/cli/ddd'
    | '/docs/cli'
    | '/docs/github-diff-viewer'
    | '/docs/share-git-diff'
    | '/view/$slug'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DRoute: typeof DRoute
  DocsRoute: typeof DocsRouteWithChildren
  GithubRoute: typeof GithubRoute
  GithubDiffViewerRoute: typeof GithubDiffViewerRoute
  InstallRoute: typeof InstallRoute
  ShareGitDiffRoute: typeof ShareGitDiffRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CliDddRoute: typeof CliDddRoute
  ViewSlugRoute: typeof ViewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d': {
      id: '/d'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof DRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-diff-viewer': {
      id: '/github-diff-viewer'
      path: '/github-diff-viewer'
      fullPath: '/github-diff-viewer'
      preLoaderRoute: typeof GithubDiffViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-git-diff': {
      id: '/share-git-diff'
      path: '/share-git-diff'
      fullPath: '/share-git-diff'
      preLoaderRoute: typeof ShareGitDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/ddd': {
      id: '/cli/ddd'
      path: '/cli/ddd'
      fullPath: '/cli/ddd'
      preLoaderRoute: typeof CliDddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/github-diff-viewer': {
      id: '/docs/github-diff-viewer'
      path: '/github-diff-viewer'
      fullPath: '/docs/github-diff-viewer'
      preLoaderRoute: typeof DocsGithubDiffViewerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/share-git-diff': {
      id: '/docs/share-git-diff'
      path: '/share-git-diff'
      fullPath: '/docs/share-git-diff'
      preLoaderRoute: typeof DocsShareGitDiffRouteImport
      parentRoute: typeof DocsRoute
    }
    '/view/$slug': {
      id: '/view/$slug'
      path: '/view/$slug'
      fullPath: '/view/$slug'
      preLoaderRoute: typeof ViewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DocsRouteChildren {
  DocsCliRoute: typeof DocsCliRoute
  DocsGithubDiffViewerRoute: typeof DocsGithubDiffViewerRoute
  DocsShareGitDiffRoute: typeof DocsShareGitDiffRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsCliRoute: DocsCliRoute,
  DocsGithubDiffViewerRoute: DocsGithubDiffViewerRoute,
  DocsShareGitDiffRoute: DocsShareGitDiffRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DRoute: DRoute,
  DocsRoute: DocsRouteWithChildren,
  GithubRoute: GithubRoute,
  GithubDiffViewerRoute: GithubDiffViewerRoute,
  InstallRoute: InstallRoute,
  ShareGitDiffRoute: ShareGitDiffRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CliDddRoute: CliDddRoute,
  ViewSlugRoute: ViewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
