/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DRouteImport } from './routes/d'
import { Route as GithubRouteImport } from './routes/github'
import { Route as GithubDiffViewerRouteImport } from './routes/github-diff-viewer'
import { Route as ShareGitDiffRouteImport } from './routes/share-git-diff'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as ViewSlugRouteImport } from './routes/view.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DRoute = DRouteImport.update({
  id: '/d',
  path: '/d',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubDiffViewerRoute = GithubDiffViewerRouteImport.update({
  id: '/github-diff-viewer',
  path: '/github-diff-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareGitDiffRoute = ShareGitDiffRouteImport.update({
  id: '/share-git-diff',
  path: '/share-git-diff',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/docs/cli',
  path: '/docs/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewSlugRoute = ViewSlugRouteImport.update({
  id: '/view/$slug',
  path: '/view/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/d': typeof DRoute
  '/github': typeof GithubRoute
  '/github-diff-viewer': typeof GithubDiffViewerRoute
  '/share-git-diff': typeof ShareGitDiffRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/cli': typeof DocsCliRoute
  '/view/$slug': typeof ViewSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/d': typeof DRoute
  '/github': typeof GithubRoute
  '/github-diff-viewer': typeof GithubDiffViewerRoute
  '/share-git-diff': typeof ShareGitDiffRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/cli': typeof DocsCliRoute
  '/view/$slug': typeof ViewSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/d': typeof DRoute
  '/github': typeof GithubRoute
  '/github-diff-viewer': typeof GithubDiffViewerRoute
  '/share-git-diff': typeof ShareGitDiffRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/docs/cli': typeof DocsCliRoute
  '/view/$slug': typeof ViewSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/d'
    | '/github'
    | '/github-diff-viewer'
    | '/share-git-diff'
    | '/sitemap.xml'
    | '/docs/cli'
    | '/view/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/d'
    | '/github'
    | '/github-diff-viewer'
    | '/share-git-diff'
    | '/sitemap.xml'
    | '/docs/cli'
    | '/view/$slug'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/d'
    | '/github'
    | '/github-diff-viewer'
    | '/share-git-diff'
    | '/sitemap.xml'
    | '/docs/cli'
    | '/view/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DRoute: typeof DRoute
  GithubRoute: typeof GithubRoute
  GithubDiffViewerRoute: typeof GithubDiffViewerRoute
  ShareGitDiffRoute: typeof ShareGitDiffRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DocsCliRoute: typeof DocsCliRoute
  ViewSlugRoute: typeof ViewSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d': {
      id: '/d'
      path: '/d'
      fullPath: '/d'
      preLoaderRoute: typeof DRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-diff-viewer': {
      id: '/github-diff-viewer'
      path: '/github-diff-viewer'
      fullPath: '/github-diff-viewer'
      preLoaderRoute: typeof GithubDiffViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-git-diff': {
      id: '/share-git-diff'
      path: '/share-git-diff'
      fullPath: '/share-git-diff'
      preLoaderRoute: typeof ShareGitDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/docs/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$slug': {
      id: '/view/$slug'
      path: '/view/$slug'
      fullPath: '/view/$slug'
      preLoaderRoute: typeof ViewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DRoute: DRoute,
  GithubRoute: GithubRoute,
  GithubDiffViewerRoute: GithubDiffViewerRoute,
  ShareGitDiffRoute: ShareGitDiffRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DocsCliRoute: DocsCliRoute,
  ViewSlugRoute: ViewSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
